<?PHP
/**
 * Project:			yourportfolio
 *
 * @link http://www.yourportfolio.nl
 * @copyright 2007 Furthermore
 * @author Joeri van Oostveen <joeri@furthermore.nl>
 */

/**
 * last file called, disconnects from the database and generates some output
 *
 * @package yourportfolio
 * @subpackage System
 */

/**
 * Load messages from MessageQueue (and will be cleared from the queue).
 */
$messages->load();

/**
 * Close session before continuing with the output.
 */
session_write_close();

/**
 * if there were some changes, we need to update the xml file
 */
if ($system->changed)
{
	$system->updateChanges();
}

/**
 * disconnect from database
 */
$db->disconnect();

/**
 * 
 */
if ($system->browser == 5)
{
	$canvas->addBodyTag('onResize', 'windowResized()');
	$canvas->addBodyTag('onLoad', 'windowResized()');
}

/**
 * premature output, output generated by code, can not be good unless in development
 */
if (DEBUG)
{
	#ob_end_flush();
} else {
	ob_end_clean();
}

/**
 * catch the next comming output
 */
ob_start();

/**
 * start html output
 */
require(HTML.'html_start.php');

/**
 * show the html template
 */
if (empty($canvas->template))
{
	$canvas->template = 'empty';
}
require(HTML.$canvas->template.'.php');

/**
 * show some debug information
 * could be helpfull when solving problems
 * calculate script end time
 */
if (DEBUG)
{
	$end_time = array_sum(explode(' ', microtime()));
	$run_time = $end_time - $start_time;
	require(HTML.'debug.php');
}

/**
 * last part of the html
 */
require(HTML.'html_stop.php');

/**
 * send some headers to prevent caching
 */
header('Last-Modified: '.gmdate("D, j M Y H:i:s T"));

// HTTP/1.1
header('Cache-Control: no-store, no-cache, must-revalidate');
header('Cache-Control: post-check=0, pre-check=0', false);

// HTTP/1.0
header('Pragma: no-cache');

/**
 * page is done, flush the toilet and exit, please lower the toilet seat
 */
ob_end_flush();

/**
 * manual publish
 */
if (isset($_GET['publish']) && (int) $_GET['publish'])
{
	$db->connect();
	$yourportfolio->update_xml();
	$yourportfolio->createGoogleSitemap();
	$db->disconnect();
}
exit();
?>